{% set data= load_setup_py_data() %}
package:
  name: ts-fbs-utils
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  script_env:
    - RUBIN_SIM_DATA_DIR={{ PREFIX }}

test:
  requires:
    - ts-conda-build =0.3
    - {{ pin_compatible('rubin-sim') }}
  source_files:
    - python
    - tests
    - setup.cfg
    - pyproject.toml
  commands:
    - rs_download_data
    - pytest -vsx tests/

requirements:
  host:
    - python {{ python }}
    - numpy {{ numpy }}
    - pip
    - setuptools_scm
    - setuptools
    - rubin-sim {{ rubin_sim }}
  build:
    - python {{ python }}
    - numpy {{ numpy }}
    - setuptools
    - setuptools_scm
    - ts-conda-build
    - rubin-sim {{ rubin_sim }}.*
  run:
    - python {{ python }}
    - {{ pin_compatible('rubin-sim') }}
