{% set data= load_setup_py_data() %}
package:
  name: ts-fbs-utils
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  script_env:
    - RUBIN_SIM_DATA_DIR={{ PREFIX }}

test:
  requires:
    - ts-conda-build =0.4
    - ts-utils
    - rubin-scheduler >=3.17.0
    - {{ pin_compatible('rubin-scheduler',  min_pin='x') }}
  source_files:
    - python
    - tests
    - setup.cfg
    - pyproject.toml
  commands:
    - scheduler_download_data --update
    - pytest -vsx tests/

requirements:
  host:
    - python {{ python }}
    - numpy {{ numpy }}
    - pip
    - setuptools_scm
    - setuptools
  build:
    - python {{ python }}
    - numpy {{ numpy }}
    - setuptools
    - setuptools_scm
    - ts-conda-build
  run:
    - python {{ python }}
    - {{ pin_compatible('rubin-scheduler', min_pin='x') }}
    - ts-utils
